services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
      - ./ollama-entrypoint.sh:/entrypoint.sh
    entrypoint: ["/entrypoint.sh"]

  app:
    build: ./app
    container_name: ai-app
    ports:
      - "8888:8888"
      - "7860-7960:7860-7960"
    depends_on:
      - ollama
    volumes:
      - ./app:/app
    working_dir: /app
    networks:
      - ai-network

volumes:
  ollama-data:

networks:
  ai-network:
    driver: bridge
